### ISSUE TITLE
发现拼写有缺失的情况

### ISSUE THREAD

**Issue by LOVAaiqg** [InfinityLoop1309/trime-jiugong#1]
用了你这个方案确实是没有了卡顿的问题，但对比原来的九宫格方案，好像损失了一些拼音组合情况
比如 连续输入两次 ‘5’键，再原来的方案中是有候选词的，但现在好像是没有了的
对比配置文件 
speller中缺失了 ‘- abbrev/^([a-z]).+$/$1/’  首字母的匹配 , 好像是加上就会有卡顿，不加就有上面我说的缺失情况

**Comment by InfinityLoop1309** [comment]
> 用了你这个方案确实是没有了卡顿的问题，但对比原来的九宫格方案，好像损失了一些拼音组合情况 比如 连续输入两次 ‘5’键，再原来的方案中是有候选词的，但现在好像是没有了的 对比配置文件 speller中缺失了 ‘- abbrev/^([a-z]).+$/$1/’ 首字母的匹配 , 好像是加上就会有卡顿，不加就有上面我说的缺失情况

我记得是卡顿的原因是可能的拼音匹配过多，所以我把相关的模糊之类都去掉了。这个问题大概无解。
