### ISSUE TITLE
如何使用语音输入功能？

### ISSUE THREAD

**Issue by dryangyq** [InfinityLoop1309/trime-jiugong#2]
我看在设置里面有语音，但是点了没反应，是需要进行额外的设置吗？
谢谢！

**Comment by InfinityLoop1309** [comment]
你好，语音输入法不是方案自带的内容，方案只是触发了`voice_assist`，其具体实现依赖于手机系统，因此其效果无法保证也超出了本方案的解决范围，详情请参看trime的issue[ 请问「同文输入法」的「语音输入」如何调用系统的「语音引擎」？ #383 ](https://github.com/osfans/trime/issues/383)
